# Site settings
title: Dan Berger's blog
email: dsberger@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:year/:month/:day/:title"
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: ""

# Social icons
twitter: dsberger
github: dsberger

footer: Â© Taken theme

# Build settings
markdown: kramdown
